name: Deploy 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: code/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy via SFTP
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            server: ${{ secrets.SFTP_HOST }}
            username: ${{ secrets.SFTP_USERNAME }}
            password: ${{ secrets.SFTP_PASSWORD }}
            port: 22
            local_path: code/dist/*
            remote_path: /
            delete_remote_files: false

